trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'epicbook-azure-rm'
  tfVersion: '1.6.6'

stages:
- stage: Terraform_Infra
  displayName: 'Provision EpicBook Infrastructure'
  jobs:
  - job: TerraformJob
    displayName: 'Terraform Init, Plan and Apply'
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform $(tfVersion)'
      inputs:
        terraformVersion: '$(tfVersion)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendType: 'local'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: '$(serviceConnection)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: '-auto-approve'